### ISSUE TITLE
Drinking water contains 4% alcohol in Wikidata

### ISSUE THREAD

**Issue by Jonasdoubleyou** [Quaffel/get-me-drunk-efficiently#21]
There must be some ingredient that is in the "drinking water" category which for some reason contains alcohol

**Comment by Quaffel** [comment]
It's even ~better~ worse: According to our data, drinking water contains 14% alcohol, not only 4%. Drinking beer should thus be encouraged.

Jokes aside: The issue is caused by the cocktail ["Canchanchara"](https://www.wikidata.org/wiki/Q96374357). For its ingredient ["drinking water"](https://www.wikidata.org/wiki/Q7892), the SPARQL query determines the Open Food Facts category "beverages". This isn't entirely wrong, but problematic for obvious reasons.

The root cause of this false claim is an optimization. Whenever an ingredient entity itself doesn't hold sufficient information (alcohol by volume or the Open Food Facts category ID), the instances and super classes of that entity are queried as well. One super class of "drinking water" is ["drink"](https://www.wikidata.org/wiki/Q40050) which has the Open Food Facts category ID "beverages".

A simple fix would be to no longer make use of this optimization for determining the Open Food Facts category ID (we can still do so for querying the alcohol by volume). Without the optimization, we would no longer query for the following **16 categories**:

```js
[
  'sparkling-wines',
  'white-wines',
  'maple-syrups',
  'wines-from-italy',
  'bananas',
  'beverages',
  'eggs',
  'berries',
  'fortified-wines',
  'sodas',
  'bird-eggs',
  'fruit-and-vegetable-preserves',
  'fruit-preserves',
  'fruit-syrups',
  'fruit-and-fruit-seed-oils',
  'breakfast-cereals'
]
```

In total, we'd lose alcohol information on the following **20 ingredients (19 without "drinking water")**:

```js
[
  { name: 'Calvados', alcohol: 0.11699999999999999 },
  { name: 'Prosecco', alcohol: 0.10400000000000001 },
  { name: 'Bacardi Carta Blanca', alcohol: 0.45799999999999996 },
  { name: 'coffee liqueur', alcohol: 0.295 },
  { name: 'drinking water', alcohol: 0.14 },
  { name: 'Lillet', alcohol: 0.132 },
  { name: 'vodka citron', alcohol: 0.38799999999999996 },
  { name: 'St. Germain', alcohol: 0.295 },
  { name: 'dry white wine', alcohol: 0.131 },
  { name: 'California brandy', alcohol: 0.387 },
  { name: 'overproof rum', alcohol: 0.455 },
  { name: 'cream liqueur', alcohol: 0.295 },
  { name: 'sweet red vermouth', alcohol: 0.132 },
  { name: 'Green Creme de Menthe', alcohol: 0.11699999999999999 },
  { name: 'orange flower water', alcohol: 0.11699999999999999 },
  { name: 'vermouth', alcohol: 0.152 },
  { name: 'Drambuie', alcohol: 0.295 },
  { name: 'Wild Turkey', alcohol: 0.4 },
  { name: 'clam juice', alcohol: 0.14 },
  { name: 'bacon vodka', alcohol: 0.38799999999999996 }
]
```

Seems like a high price to pay. Do you have any other ideas on how to approach this problem?

@nhaef Might be interesting for you as well...

**Comment by Jonasdoubleyou** [comment]
can we exclude the category "beverages" or in general anything coming from "drink"? That seems to generic to be useful
